Update to v2.0_beta
- main update to v2
- multi pdb file processing
- ramp visualization enabled
- some new flags

- however bug in ramp if higher size

diff --git a/pHmap b/pHmap
--- a/pHmap
+++ b/pHmap
@@ -1,7 +1,9 @@
 #!/bin/bash
 #
-# ARG_POSITIONAL_INF([ph_range],[range of pH's; start steps stop e.g. 5 0.5 7]))
-# ARG_OPTIONAL_SINGLE([pdb],[p],[input pdb file])
+# ARG_POSITIONAL_INF([pdb],[pdb files to process)],[1])
+# ARG_POSITIONAL_DOUBLEDASH([])
+
+# ARG_OPTIONAL_SINGLE([ph_range],[r],[range of pH's in quotes!; 'start stop step' e.g. '5 7 0.5'])
 # ARG_OPTIONAL_SINGLE([ligand],[l],[input mol2 file])
 # ARG_OPTIONAL_SINGLE([set_view],[s],[imports view settings from file; input file must contain\nthe PyMol output of the get_view command!])
 
@@ -17,14 +19,15 @@
 # ARG_OPTIONAL_SINGLE([stretch],[],[font stretch; type  <convert -list stretch>\n to get a list of available stretch settings\n],[Normal])
 # ARG_OPTIONAL_SINGLE([style],[],[font style; type  <convert -list style>\n to get a list of available style settings\n],[Normal])
 
-# ARG_OPTIONAL_SINGLE([alignment],[],[alignment of the axis text: West, Center, East\n],[Center])
+# ARG_OPTIONAL_BOOLEAN([ramp],[],[enable/disable ramp\n],[on])
+# ARG_OPTIONAL_SINGLE([xalign],[],[x-axis alignment of the pH value text; type  <convert -list gravity>\n to get a list of available alignment settings\n],[Center])
+# ARG_OPTIONAL_SINGLE([yalign],[],[y-axis alignment of the label text; type  <convert -list gravity>\n to get a list of available alignment settings\n],[Center])
 # ARG_OPTIONAL_SINGLE([size],[],[individual picture size: default means 500x500 pixel (quadratic; 300 dpi)\n],[500])
 # ARG_OPTIONAL_SINGLE([background],[],[background color: None, colors e.g. white, black])
 
-# ARG_HELP([+-------+\n| pHmap |\n+-------+\nby Erik Breslmayr, 2020\n \npHmap uses pdb2pqr, apbs to calcualte electrostatic surface potentials,\nwhich are visualized by generating 2D pictures with PyMol. Several pH\nvalues can be processed and will be combined into one figure. As x-Axis\nof the picture pH-profile the pH values will be added.\n])
-# ARG_VERSION([echo $0 v1.1.1])
+# ARG_HELP([+-------+\n| pHmap |\n+-------+\nby Erik Breslmayr, 2020\n \npHmap uses pdb2pqr, apbs to calcualte electrostatic surface potentials,\nwhich are visualized by generating 2D pictures with PyMol. Several pH's\nand pdb files can be processed and will be combined into one figure. On\nthe x-axis the pH's and on the y-axis the filenames will be added.\n \nExamples:\npHmap protein.pdb mutant.pdb -r '4 7 0.5' -l ligand.mol2 -s set_view.txt\npHmap protein.pdb mutant.pdb -r '4 7 0.5' -l ligand.mol2 -s set_view.txt --axis_update --font Helvetica --fontsize 60\npHmap protein.pdb mutant.pdb -r '4 7 0.25' -l ligand.mol2 -s set_view.txt --digits 2\n])
+# ARG_VERSION([echo $0 v2.0_beta])
 # ARG_OPTIONAL_REPEATED([include],[I],[Directory for temporary folder],['/tmp'])
-
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
 ### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
@@ -43,16 +46,16 @@ die()
 
 begins_with_short_option()
 {
-	local first_option all_short_options='plshvI'
+	local first_option all_short_options='rlshvI'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
 # THE DEFAULTS INITIALIZATION - POSITIONALS
 _positionals=()
-_arg_ph_range=()
+_arg_pdb=('' )
 # THE DEFAULTS INITIALIZATION - OPTIONALS
-_arg_pdb=
+_arg_ph_range=
 _arg_ligand=
 _arg_set_view=
 _arg_level="5"
@@ -65,7 +68,9 @@ _arg_fontsize="40"
 _arg_weight="Normal"
 _arg_stretch="Normal"
 _arg_style="Normal"
-_arg_alignment="Center"
+_arg_ramp="on"
+_arg_xalign="Center"
+_arg_yalign="Center"
 _arg_size="500"
 _arg_background=
 _arg_include=('/tmp')
@@ -79,13 +84,18 @@ print_help()
 by Erik Breslmayr, 2020
 
 pHmap uses pdb2pqr, apbs to calcualte electrostatic surface potentials,
-which are visualized by generating 2D pictures with PyMol. Several pH
-values can be processed and will be combined into one figure. As x-Axis
-of the picture pH-profile the pH values will be added.
+which are visualized by generating 2D pictures with PyMol. Several pH's
+and pdb files can be processed and will be combined into one figure. On
+the x-axis the pH's and on the y-axis the filenames will be added.
+
+Examples:
+pHmap protein.pdb mutant.pdb -r '4 7 0.5' -l ligand.mol2 -s set_view.txt
+pHmap protein.pdb mutant.pdb -r '4 7 0.5' -l ligand.mol2 -s set_view.txt --axis_update --font Helvetica --fontsize 60
+pHmap protein.pdb mutant.pdb -r '4 7 0.25' -l ligand.mol2 -s set_view.txt --digits 2
 "
-	printf 'Usage: %s [-p|--pdb <arg>] [-l|--ligand <arg>] [-s|--set_view <arg>] [--level <arg>] [--rampcolors <arg>] [--(no-)surface_above] [--(no-)axis_update] [--digits <arg>] [--font <arg>] [--fontsize <arg>] [--weight <arg>] [--stretch <arg>] [--style <arg>] [--alignment <arg>] [--size <arg>] [--background <arg>] [-h|--help] [-v|--version] [-I|--include <arg>] [<ph_range-1>] ... [<ph_range-n>] ...\n' "$0"
-	printf '\t%s\n' "<ph_range>: range of pH's; start steps stop e.g. 5 0.5 7"
-	printf '\t%s\n' "-p, --pdb: input pdb file (no default)"
+	printf 'Usage: %s [-r|--ph_range <arg>] [-l|--ligand <arg>] [-s|--set_view <arg>] [--level <arg>] [--rampcolors <arg>] [--(no-)surface_above] [--(no-)axis_update] [--digits <arg>] [--font <arg>] [--fontsize <arg>] [--weight <arg>] [--stretch <arg>] [--style <arg>] [--(no-)ramp] [--xalign <arg>] [--yalign <arg>] [--size <arg>] [--background <arg>] [-h|--help] [-v|--version] [-I|--include <arg>] [--] <pdb-1> [<pdb-2>] ... [<pdb-n>] ...\n' "$0"
+	printf '\t%s\n' "<pdb>: pdb files to process)"
+	printf '\t%s\n' "-r, --ph_range: range of pH's in quotes!; 'start stop step' e.g. '5 7 0.5' (no default)"
 	printf '\t%s\n' "-l, --ligand: input mol2 file (no default)"
 	printf '\t%s\n' "-s, --set_view: imports view settings from file; input file must contain
 		the PyMol output of the get_view command! (no default)"
@@ -112,7 +122,13 @@ of the picture pH-profile the pH values will be added.
 	printf '\t%s\n' "--style: font style; type  <convert -list style>
 		 to get a list of available style settings
 		 (default: 'Normal')"
-	printf '\t%s\n' "--alignment: alignment of the axis text: West, Center, East
+	printf '\t%s\n' "--ramp, --no-ramp: enable/disable ramp
+		 (on by default)"
+	printf '\t%s\n' "--xalign: x-axis alignment of the pH value text; type  <convert -list gravity>
+		 to get a list of available alignment settings
+		 (default: 'Center')"
+	printf '\t%s\n' "--yalign: y-axis alignment of the label text; type  <convert -list gravity>
+		 to get a list of available alignment settings
 		 (default: 'Center')"
 	printf '\t%s\n' "--size: individual picture size: default means 500x500 pixel (quadratic; 300 dpi)
 		 (default: '500')"
@@ -131,17 +147,27 @@ parse_commandline()
 	while test $# -gt 0
 	do
 		_key="$1"
+		if test "$_key" = '--'
+		then
+			shift
+			test $# -gt 0 || break
+			_positionals+=("$@")
+			_positionals_count=$((_positionals_count + $#))
+			shift $(($# - 1))
+			_last_positional="$1"
+			break
+		fi
 		case "$_key" in
-			-p|--pdb)
+			-r|--ph_range)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-				_arg_pdb="$2"
+				_arg_ph_range="$2"
 				shift
 				;;
-			--pdb=*)
-				_arg_pdb="${_key##--pdb=}"
+			--ph_range=*)
+				_arg_ph_range="${_key##--ph_range=}"
 				;;
-			-p*)
-				_arg_pdb="${_key##-p}"
+			-r*)
+				_arg_ph_range="${_key##-r}"
 				;;
 			-l|--ligand)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
@@ -237,13 +263,25 @@ parse_commandline()
 			--style=*)
 				_arg_style="${_key##--style=}"
 				;;
-			--alignment)
+			--no-ramp|--ramp)
+				_arg_ramp="on"
+				test "${1:0:5}" = "--no-" && _arg_ramp="off"
+				;;
+			--xalign)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-				_arg_alignment="$2"
+				_arg_xalign="$2"
 				shift
 				;;
-			--alignment=*)
-				_arg_alignment="${_key##--alignment=}"
+			--xalign=*)
+				_arg_xalign="${_key##--xalign=}"
+				;;
+			--yalign)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_yalign="$2"
+				shift
+				;;
+			--yalign=*)
+				_arg_yalign="${_key##--yalign=}"
 				;;
 			--size)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
@@ -270,11 +308,11 @@ parse_commandline()
 				exit 0
 				;;
 			-v|--version)
-				echo $0 v1.1.1
+				echo $0 v2.0_beta
 				exit 0
 				;;
 			-v*)
-				echo $0 v1.1.1
+				echo $0 v2.0_beta
 				exit 0
 				;;
 			-I|--include)
@@ -299,14 +337,21 @@ parse_commandline()
 }
 
 
+handle_passed_args_count()
+{
+	local _required_args_string="'pdb'"
+	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+}
+
+
 assign_positional_args()
 {
 	local _positional_name _shift_for=$1
-	_positional_names=""
-	_our_args=$((${#_positionals[@]} - 0))
+	_positional_names="_arg_pdb "
+	_our_args=$((${#_positionals[@]} - 1))
 	for ((ii = 0; ii < _our_args; ii++))
 	do
-		_positional_names="$_positional_names _arg_ph_range[$((ii + 0))]"
+		_positional_names="$_positional_names _arg_pdb[$((ii + 1))]"
 	done
 
 	shift "$_shift_for"
@@ -319,6 +364,7 @@ assign_positional_args()
 }
 
 parse_commandline "$@"
+handle_passed_args_count
 assign_positional_args 1 "${_positionals[@]}"
 
 # OTHER STUFF GENERATED BY Argbash
@@ -326,26 +372,34 @@ assign_positional_args 1 "${_positionals[@]}"
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
 
-
 ## Variables
 SECONDS=0
 TEMP="$_arg_include"
 WPATH="$(pwd)"
 
 ### arguments var
+#### ligandFlag
+if [[ -n "$_arg_ligand" ]]; then
+    ligandFlag=$(echo --ligand=$_arg_ligand)
+fi
+
+#### set_view
 if [[ -z "$_arg_set_view" ]]; then
     view=" "
 else
     view=$(cat $_arg_set_view)
 fi
-#### pH range
-pHmin=$(printf "%.${_arg_digits}f" ${_arg_ph_range[0]}) # pH values
-pHinc=$(printf "%.${_arg_digits}f" ${_arg_ph_range[1]}) # increment for range with digits to choose
-pHmax=$(printf "%.${_arg_digits}f" ${_arg_ph_range[2]}) # pH values
+#### range
+rangeMin=$(echo ${_arg_ph_range} | cut -d " " -f 1)
+rangeMax=$(echo ${_arg_ph_range} | cut -d " " -f 2)
+rangeInc=$(echo ${_arg_ph_range} | cut -d " " -f 3)
+pHmin=$(printf "%.${_arg_digits}f" $rangeMin) # pH values
+pHinc=$(printf "%.${_arg_digits}f" $rangeInc) # increment for range with digits to choose
+pHmax=$(printf "%.${_arg_digits}f" $rangeMax) # pH values
 
 for i in `seq $pHmin $pHinc $pHmax`; do
     pHrange=$(printf "%.${_arg_digits}f\n" $pHrange $i)
-done
+done >/dev/null 2>/dev/null
 #### pymol settings
 if [ $_arg_surface_above = "off" ]; then
     above_mode=" "
@@ -353,7 +407,7 @@ else
     above_mode="set surface_ramp_above_mode"
 fi
 #### convert settings
-axisPageSize=$(echo $_arg_fontsize*1.25 | bc) # axispagehighnes is 1.25 times higher then fontsize
+axisPageSize=$(echo $_arg_fontsize*1.25 | bc -l) # axispagehighnes is 1.25 times higher then fontsize
 backGround="$_arg_background" # background color
 if [[ -z "$backGround" ]]; then
     backGroundTrans="off"
@@ -365,33 +419,37 @@ fi
 ## Functions
 timeNeed () {
 ELAPSED="$(($SECONDS / 3600))hrs $((($SECONDS / 60) % 60))min $(($SECONDS % 60))sec"
-printf "|%-30s%30s|\n" "Program finished within:" "$ELAPSED"
+printf "|%-30s%30s|\n\n" "Program finished within:" "$ELAPSED"
 }
 
 check () {
 #checks if pdb file is given
-
-if [[ -z "$_arg_pdb" ]]; then
-	printf "$emptyFormat" "       !no pdb file given!"
-	printf "$emptyFormat" "      pHmap -h for help!"
+if [[ -z "$rangeMin" ]] && [[ -z "$rangeMax" ]] && [[ -z "$rangeInc" ]]; then
+	printf "\n|%-60s|\n" "                   error in -r, --ph_range"
+	printf "|%-60s|\n\n" "                     pHmap -h for help!"
 else
     runScript
 fi
 }
 
 picGen () {
+for l in ${_arg_pdb[*]}; do
+    printf "|%-30s%30s|\n" "Processing file:" "$l"
+    label=$(echo $l | cut -d "." -f 1)
+    for i in $pHrange; do
+        printf "|%5s%-35s%20s|\n" "" "Running pdb2pqr @" "pH $i"
+        pdb2pqr --with-ph=$i --ph-calc-method=propka --drop-water --apbs-input --ff=parse $ligandFlag $l $label-$i-p2p.pqr > $label-p2p-stout.log 2> $label-p2p-sterr.log
+        sleep 1s
+        printf "|%5s%-35s%20s|\n" "" "Running apbs @" "pH $i"
+        apbs --output-file=$label-$i-apbs.log $label-$i-p2p.in > $label-apbs-stout.log 2> $label-apbs-sterr.log
+        sleep 1s
 
-for i in $pHrange; do
-    pdb2pqr --with-ph=$i --ph-calc-method=propka --drop-water --apbs-input --ff=parse --verbose --ligand=$_arg_ligand $_arg_pdb $i-p2p.pqr
-    sleep 1s
-    apbs --output-file=$i-apbs.log $i-p2p.in
-    sleep 1s
-
-    printf "
-load $i-p2p.pqr.dx
-load $i-p2p.pqr
+        printf "
+load $label-$i-p2p.pqr.dx
+load $label-$i-p2p.pqr
 as surface
-ramp_new ramp, $i-p2p.pqr, [-$_arg_level, 0, $_arg_level], [$_arg_rampcolors]
+show sticks, hetatm
+ramp_new ramp, $label-$i-p2p.pqr, [-$_arg_level, 0, $_arg_level], [$_arg_rampcolors]
 set surface_color, ramp
 $above_mode
 disable ramp
@@ -400,26 +458,63 @@ center
 zoom
 set opaque_background, $backGroundTrans
 bg_color $backGround
-png $i-pic.png, width=$_arg_size, height=$_arg_size, dpi=300" > rendering.pml
+png $label-$i-pic.png, width=$_arg_size, height=$_arg_size, dpi=300
+hide everything
+enable ramp
+png rawRamp.png, width=$_arg_size, height=$_arg_size, dpi=300"> rendering.pml
 
-    pymol -cq rendering.pml
+        printf "|%5s%-35s%20s|\n" "" "Rendering figure with PyMol @" "pH $i"
+        pymol -cq rendering.pml > $label-pymol-stout.log 2> $label-pymol-sterr.log
+    done
+    list=$(ls -tr $WPATH/$label-*-pic.png)
+    convert +append $list $label-pH_profile_pic.png
 done
 }
 
 numGen () {
 for i in $pHrange; do
-    convert -size ${_arg_size}x$axisPageSize -gravity $_arg_alignment -background  $backGround -weight $_arg_weight -stretch $_arg_stretch -style $_arg_style -pointsize $_arg_fontsize -family $_arg_font label:$i $WPATH/$i-number.png
+    convert -size ${_arg_size}x$axisPageSize -gravity $_arg_xalign -background  $backGround -weight $_arg_weight -stretch $_arg_stretch -style $_arg_style -pointsize $_arg_fontsize -family $_arg_font label:$i $WPATH/$i-number.png
 done
 }
 
+labelGen () {
+for i in ${_arg_pdb[*]}; do
+    label=$(echo $i | cut -d "." -f 1)
+    convert -size ${_arg_size}x${_arg_size} -gravity $_arg_yalign -background  $backGround -weight $_arg_weight -stretch $_arg_stretch -style $_arg_style -pointsize $_arg_fontsize -family $_arg_font label:$label $WPATH/$label-label.png
+done
+}
+
+emptyGen () {
+    convert -size ${_arg_size}x$axisPageSize xc:None empty.png
+}
+rampGen () {
+    rampWidthFactor=$(echo $_arg_size/500 | bc -l) # 500 is default --size flag!!!
+    rampHigh=$(echo $axisPageSize*$rampWidthFactor | bc -l)
+    offset=$(echo $rampHigh/4.545454545 | bc -l) # from fontsize 40 comes 50 for axisPageSize and 11 is needed as offset, therefore 50/11 as factor to center ramp.
+
+    convert rawRamp.png -gravity South -crop ${_arg_size}x${rampHigh}+0+$offset -gravity Center -resize ${_arg_size}x$rampHigh -background $backGround -compose Copy -extent ${_arg_size}x$rampHigh ramp.png
+
+    ### bug in empty and x axis if higher size!!!
+}
 
 picCombine () {
-list=$(ls -tr $WPATH/*-pic.png)
-convert +append $list pH_profile_pic.png
+printf "\n|%-60s|\n" "Generating final figure and cleaning up"
+#xaxis
 list=$(ls -tr $WPATH/*-number.png)
-convert +append $list pH_profile_number.png
-convert -append pH_profile_pic.png pH_profile_number.png pH_profile.png
+convert +append $list xaxis_number.png
+#yaxis
+list=$(ls -tr $WPATH/*-label.png)
+if [ $_arg_ramp = "on" ]; then
+    convert -append $list ramp.png yaxis_label.png
 
+else
+    convert -append $list empty.png yaxis_label.png
+fi
+#pic and xaxis
+list=$(ls -tr *-pH_profile_pic.png)
+convert -append $list xaxis_number.png pH_profile.png
+#pic, xaxis and yaxis
+convert +append yaxis_label.png pH_profile.png pH_profile+label.png
 }
 
 cleanUp () {
@@ -428,23 +523,36 @@ mkdir p2pFiles >/dev/null 2>/dev/null
 mkdir logFiles >/dev/null 2>/dev/null
 mkdir pngFiles >/dev/null 2>/dev/null
 
-mv *-apbs.log logFiles >/dev/null 2>/dev/null
+mv *.log logFiles >/dev/null 2>/dev/null
 mv *p2p* p2pFiles >/dev/null 2>/dev/null
 mv *-pic.png pngFiles >/dev/null 2>/dev/null
 mv *-number.png pngFiles >/dev/null 2>/dev/null
+mv *-label.png pngFiles >/dev/null 2>/dev/null
 rm io.mc >/dev/null 2>/dev/null
 }
 
 ## SCRIPT
 runScript () {
+date=$(date)
+printf "\n|%-30s%30s|\n\n" "pHmap started @" "$date"
+
+
 if [ $_arg_axis_update = "on" ]; then
+    # only run convert
     WPATH=$(echo $WPATH/pngFiles)
     rm $WPATH/*-number.png >/dev/null 2>/dev/null
+    rm $WPATH/*-label.png >/dev/null 2>/dev/null
     numGen
+    labelGen
+    emptyGen
+    rampGen
     picCombine
 else
     picGen
     numGen
+    labelGen
+    emptyGen
+    rampGen
     picCombine
 fi
 cleanUp
